### ISSUE TITLE
Support VendorOption Tags

### ISSUE THREAD

**Issue by glenselle** [geostyler/geostyler#1118]
### Description:

I'm creating text symbolizers which look like this:
```javascript
{
    color: "#000",
    font: ["Arial"],
    fontStyle: "normal",
    fontWeight: "bold",
    haloColor: "#fff",
    haloWidth: 1,
    kind: "Text",
    label: "{{name}}",
    size: 12
}
````

My backend is a geoserver instance and I need to send along some `VendorOption` tags which will control label placement. I know that these tags are not technically part of the SLD spec. 

```<VendorOption name="spaceAround">-1</VendorOption>```

Here are the tags from the geoserver docs which I'm referring to: https://docs.geoserver.org/stable/en/user/styling/sld/reference/labeling.html#overlapping-and-separating-labels-spacearound

Would it be possible to extend text symbolizers so you could pass custom tags through? I would be willing to contribute a PR for this if this is possible and would be merged. I'm open to whatever means the owners think would be best to support this, if at all.

Thanks!

**Comment by hwbllmnn** [comment]
I've spoken to other people at a code sprint we're having right now, and they're also of the opinion that having some kind of extension mechanism would be nice. Perhaps introducing some vendor option like that in order to promote established properties to 'proper' properties later on would be nice (idea stolen from @jodygarnett). If you want to tackle this, you'd be very welcome! What do others think @KaiVolland @dnlkoch ?

**Comment by KaiVolland** [comment]
IMHO extending the [TextSymbolizer](https://github.com/terrestris/geostyler-style/blob/master/index.d.ts#L158) should be the way to go.
@glenselle would be nice if you could open a PR to add `spaceAround` to [style](https://github.com/terrestris/geostyler-style) and [SLD-Parser](https://github.com/terrestris/geostyler-sld-parser).

**Comment by chrismayer** [comment]
I like the idea of introducing a kind of extension mechanism, e.g. to use some vendor specific properties without adapting the code.

Do we want a specific solution for the mentioned GeoServer properties like `spaceAround` or do we want to have a generic approach to allow app devs using GeoStyler to introduce their own custom properties (maybe by offering some overwriteable transformer functions or similar)? Or does this open up the door to hell?
Totally +1 for adding the GeoServer vendor options. The generic approach is open for discussion.

**Comment by jodygarnett** [comment]
A couple of notes since we have prior experience to draw from:

* property names should use `a_consistent` `NamingConvention`  (personally I prefer `space_around` so property name is not case sensitive)
* For GeoServer CSS we started by clearly marking "custom" things with a prefix, before making it everything consistent (see `label-padding` on [Property listing] )(https://docs.geoserver.org/latest/en/user/styling/css/properties.html)
* For YLSD we used a prefix for any vendor options (see `x-spaceAround` on [TextSymbolizer](https://docs.geoserver.org/latest/en/user/styling/ysld/reference/symbolizers/text.html) )

**Comment by jodygarnett** [comment]
Some discussion from code sprint:

* expressions *everywhere* discussion with @glenselle volaya
* [dynamic symbolizers](https://docs.geoserver.org/stable/en/user/styling/sld/extensions/pointsymbols.html#dynamic-symbolizers) Use of expressions to configure external graphics 
* Parameterized SVG graphics (where expressions are used to control the colors used by different parts of the SVG
* [Color compositing and color blending](https://docs.geoserver.org/latest/en/user/styling/sld/extensions/composite-blend/index.html) - covers rendering into individual buffers and then special effects between buffers

**Comment by jodygarnett** [comment]
So if I understand correctly:

```javascript
export interface TextSymbolizer extends BasePointSymbolizer {
  kind: 'Text';
  allowOverlap?: boolean;
  ...
  vendorOptions?: { string: Any }
}
```

**Comment by KaiVolland** [comment]
I'm a bit afraid that we are making things to complicated if we add a blackbox object to the style definition. We have to keep in mind that we're not only translating `geostyler-style` to `sld` and back.

How should a parser know how to treat an unknown property?

If a property makes sense for styling a Text. Lets just add it directly to the TextSymbolizer.

We are not limited to the SLD specification.

As the [sld-parser](https://github.com/terrestris/geostyler-sld-parser) **is** limited, i'd prefer the idea to have a `geostyler-geoserver-sld-parser` that extends the current sld-parser and adds parsing of the geoserver vendor options.

**Comment by glenselle** [comment]
@KaiVolland If there was a `geostyler-geoserver-sld-parser` (which does make a lot of sense in order to keep `sld-parser` slim & non-specific to vendor-added things) how do you envision the vendor properties be represented in the resulting geostyle object?

**Comment by glenselle** [comment]
```javascript
// simplified example of the parser class in `sld-parser`
class SldStyleParser {
  getTextSymbolizer() {
    return {
      label: '{{name}}'
    }
  }
}
// simplified example of the possible new parser class `geostyler-geoserver-sld-parser`
class GeoserverSldStyleParser extends SldStyleParser {
  getTextSymbolizer() {
    return {
      ...super.getTextSymbolizer(),
      vendorOptions: {
        spaceAround: -1
      }
    }
  }
}

// this obviously would be done internally...not a public API -- just an example
const parser = new GeoserverSldStyleParser()
parser.getTextSymbolizer()
// I don't know how we'd represent these vendor options in the resulting object
// but this is one way similar to the @jodygarnett example
// { label: '{{name}}', vendorOptions: { spaceAround: -1 } }
```

**Comment by KaiVolland** [comment]
> how do you envision the vendor properties be represented in the resulting geostyle object?

I really like to keep it simple here. So adding the `spaceAround` property would look like this:

```ts
diff --git a/index.d.ts b/index.d.ts
index 9917457..9a13ed5 100644
--- a/index.d.ts
+++ b/index.d.ts
@@ -177,6 +177,7 @@ export interface TextSymbolizer extends BasePointSymbolizer {
   rotate?: number;
   rotationAlignment?: 'map' | 'viewport' | 'auto';
   size?: number;
+  spaceAround?: number;
   transform?: 'none' | 'uppercase' | 'lowercase';
   fontStyle?: 'normal' | 'italic' | 'oblique';
   fontWeight?: 'normal' | 'bold';
```

No extra object with key `vendorOptions` is needed. The `geostyler-style` is not bound to the SLD so actually there are no `vendorOptions`.

-----

[Your parser snippet](https://github.com/terrestris/geostyler/issues/1118#issuecomment-505942326) looks just as I imagined it would be  :heart_eyes:. (Accept the part with the `vendorOptions`.)

There are two things we should do:
 - Enhance the documentation of geostyler-style #1119 
 - Implement the [UnsupportedProperties](https://github.com/terrestris/geostyler-style/blob/master/index.d.ts#L357) interface for every parser #1120

Appreciate if you also share your thoughts on these two issues.

**Comment by chrismayer** [comment]
Great discussion guys :+1: Thank you all! Here some thoughts of mine:

I really like the idea of having an `GeoserverSldStyleParser` extending the `SldStyleParser` as an internal interface like proposed by @glenselle and @KaiVolland.

Regarding the modelling of the properties:
@KaiVolland is totally right (and I really often have to remind myself): We are not bound (only) to SLD and thus the `geostyler-style` has no vendor-specific properties (in the meaning we have them in GeoServer) since a parser always interprets only a subset of the properties.
But: Maybe it is good idea to prefix those properties, which are directly connected to a specific software / platform (like the GeoServer vendor options)? Based on @jodygarnett's suggestion to prefix custom properties? Having `gs-x-space-around` / `gsXSpaceAround` might give a hint where this might come from and apply to? Just thinking loud at the moment :wink: Any thoughts?

**Comment by jansule** [comment]
> But: Maybe it is good idea to prefix those properties, which are directly connected to a specific software / platform (like the GeoServer vendor options)? Based on @jodygarnett's suggestion to prefix custom properties? Having `gs-x-space-around` / `gsXSpaceAround` might give a hint where this might come from and apply to?

@chrismayer  I'm not sure if this is the best way to go. As you already said, we are not bound (only) to SLD and other style formats might support the same functionality (under a different name). Prefixing properties might lead to people thinking that this property is only supported by a certain style format, which is not necessarily the case.

**Comment by hwbllmnn** [comment]
Maybe the name `vendorOptions` is a bit misleading. I think having something like `customAttributes` would enable someone to use the styling model even with properties the styling model does not yet have.

Of course just adding the attributes to the styling model is always better than using the `customAttributes`, but it may be useful for someone experimenting with new ones (and perhaps not being sure about the right way to go at it yet).

Still, since the GeoServer options are already established adding them to our model would be a good addition I think.

**Comment by KaiVolland** [comment]
I'm against having anything blackbox-like in the `geostyler-style`.

If you want to have `customAttributes` then you could extend the `geostyler-style` and use this declaration with your also custom parsers.

I'm also afraid of building a proper UI component for a blackbox object.

**Comment by hwbllmnn** [comment]
> I'm also afraid of building a proper UI component for a blackbox object.

I'd definitely leave those out of the standard UI. I thought of them more like an extension mechanism (something SLD/SE is IMHO badly missing and one of the reasons we're doing this in the first place).

**Comment by chrismayer** [comment]
> Prefixing properties might lead to people thinking that this property is only supported by a certain style format, which is not necessarily the case.

@jansule Maybe you are right. Technically no problem if they are prefixed but maybe "parser devs" might be mislead by the prefix. Maybe focussing on a proper documentation (as proposed in #1119) and giving some hint from the origin of the property and what it means is the better way.

**Comment by jodygarnett** [comment]
> I'm a bit afraid that we are making things to complicated if we add a blackbox object to the style definition. We have to keep in mind that we're not only translating `geostyler-style` to `sld` and back.

Perhaps vendor option was not the best name for the capability, would like to have a "play area" to the data structure before we are in a position strictly define a property. It could be call "hints" if that was better understood...

**Comment by KaiVolland** [comment]
Im still afraid that we might open pandoras box with this.

But nevertheless here is a little adopted version of @jodygarnett  [proposed change](https://github.com/terrestris/geostyler/issues/1118#issuecomment-505867552).
`any` is replaced with `JSONValue` to avoid values like `new Date()` to be a valid.

```ts
type JSONValue = string | number | boolean | JSONObject | JSONArray;
interface JSONObject {
    [x: string]: JSONValue;
}
interface JSONArray extends Array<JSONValue> { }

/**
 * A Symbolizer describes the style representation of geographical data.
 */
interface BaseSymbolizer {
  kind: SymbolizerKind;
  color?: string;
  opacity?: number;
  translate?: [number, number];
  translateAnchor?: 'map' | 'viewport';
  visibility?: boolean;
  customAttributes?: {
    [property: string]: JSONValue
  };
}
```

**Comment by jansule** [comment]
To get things a little on track @KaiVolland, @chrismayer and I propose to directly specify the geoserver vendorOptions in the correct places as described in https://github.com/terrestris/geostyler/issues/1118#issuecomment-506239726 in [geostyler-style](https://github.com/terrestris/geostyler-style).

@glenselle we would be happy if you could provide a PR for this.

Additional opinions and comments regarding the `customAttributes` topic are very welcome here, so we can find a satisfying solution for that as well.

**Comment by KaiVolland** [comment]
@glenselle If you implement `spaceAround` we should think about removing `allowOverlap` as it almost does the the same but `spaceAround` is even more precise.

**Comment by glenselle** [comment]
@jansule sounds good. If I have time this weekend I may take a crack at it. Is the expectation that I would also create the geoserver specific parser in addition to the change in geostyler? Would that be created under the terrestris org/group?

**Comment by KaiVolland** [comment]
Any work is welcome.
Creating the extended parser would be very cool. But as it is your work it would stay at your account. At least for the first approach.
We already had some talks about creating a "GeoStyler" group on github. If we launch it, it may make sense to move all parsers to this new group. This would also apply to your (future) parser, if your ok with that.

**Comment by glenselle** [comment]
I thought I'd update this thread because we created the parser just like we talked about here. We're currently in the process of getting approval from some internal folks before it can be made public. When it gets approved I'll post back here.

**Comment by glenselle** [comment]
So good news! We finally got all the approvals we needed to get everything out. Repo is here: https://github.com/MonsantoCo/geostyler-geoserver-sld-parser we're working on getting it published on NPM ASAP. I'm going to close this issue since I think it's fair to say the solution is to create special-built parsers for things like this.

**Comment by jodygarnett** [comment]
I am not quite sure I understand the solution? Can you clarify please ...

**Comment by glenselle** [comment]
@jodygarnett see below/above comments in this thread

https://github.com/geostyler/geostyler/issues/1118#issuecomment-505875470
> As the sld-parser is limited, i'd prefer the idea to have a geostyler-geoserver-sld-parser that extends the current sld-parser and adds parsing of the geoserver vendor options.

https://github.com/geostyler/geostyler/issues/1118#issuecomment-506267929
> I really like the idea of having an GeoserverSldStyleParser extending the SldStyleParser as an internal interface like proposed by @glenselle and @KaiVolland.

https://github.com/geostyler/geostyler/issues/1118#issuecomment-507136432
> Any work is welcome. Creating the extended parser would be very cool. But as it is your work it would stay at your account. At least for the first approach.

If folks are using geoserver you would use the geoserver-geostyler parser which extends the base geostyler parser but also adds support for vendor options:
https://github.com/MonsantoCo/geostyler-geoserver-sld-parser/blob/master/src/GeoserverSldStyleParser.ts#L9

The README of the package has an example.

**Comment by jodygarnett** [comment]
Thank you I understand now :)

I would very much like to align how he vendor options are parsed now that our bridge plugin (and associated python library) is nearing release.

**Comment by glenselle** [comment]
Is there a place where I can get info on the bridge plugin? I know there was a lot of good convo in this issue initially, so if there's a better way to do vendor options going forward let us know if there's anything we could do to help 👍

**Comment by jodygarnett** [comment]
Please reach out to @volaya on the [bridge-style](https://github.com/GeoCat/bridge-style) project. 

I am sorry we have been so quiet, it really feels like everything has come together and we finally have a good progress to collaborate from.

Perhaps you both could setup a jitsi meeting in the next two weeks?

**Comment by elanioazul** [comment]
Hi,
- I downloaded @glenselle repo and altough I see it in my package.json I can not see it in node_modules, so I cannot extend the geostyler-sld-parser. Why?
- I am wondering also whether for what I want (using SLDParser to read my sld styles and OpenLayerParse to write openlayers styles, but not using GeoServer styling) this @glenselle repo is usefull for me to implement p.e. the VendorOption "followLine" enhancement.
- Becasue I am begginer, I wonder what is a possible procedure to follow to extend a class when I see a tag of a sld file that has not been succesfully translated into my output OL style... p.e. this VendorOption "followLine".
How to see if is because SLDParser is not reading correctly (not developed that specific style conversion to geostyler) or is because of the geostyler-openlayers-parser?

Thanks for contributing to my learning curve

**Comment by jansule** [comment]
Hi @elanioazul,

> I am wondering whether for what I want (using SLDParser to read my sld styles and OpenLayerParse to write openlayers styles, but not using GeoServer styling) this @glenselle repo is usefull for me to implement p.e. the VendorOption "followLine" enhancement.

I am not sure why you want to parse GeoServer specific options (vendorOptions), if you do not want to use GeoServer styling. But if you want to use vendorOptions, then yes, that would be the right package to use.

> Becasue I am begginer, I wonder what is a possible procedure to follow to extend a class when I see a tag of a sld file that has not been succesfully translated into my output OL style... p.e. this VendorOption "followLine".
How to see if is because SLDParser is not reading correctly (not developed that specific style conversion to geostyler style) or is because of the geostyler-openlayers-parser?

IMHO the best approach would be to add a PR to the repo posted in https://github.com/geostyler/geostyler/issues/1118#issuecomment-581587057 that adds the parsing of the "followLine" property, if it is missing there. You would also have to make a PR to the https://github.com/geostyler/geostyler-style that adds the type definition for the "followLine" property. Thereby the community directly profits from your work.

**Comment by fgravin** [comment]
Hi here, thanks for the work done in `geostyler-geoserver-sld-parser` but to me the documentation is misleading.
I was expecting it supports the `vendorOptions` but it seems only `TextSymbolizer` is covered.
I would like to use `graphic-margin` on `GraphicFill` like [here](https://docs.geoserver.org/latest/en/user/styling/sld/extensions/margins.html) 

I'm thinking of doing a PR, however the comment 

> You would also have to make a PR to the https://github.com/geostyler/geostyler-style that adds the type definition for the "followLine" property. Thereby the community directly profits from your work

is confusing, if I extend the `MarkSymbolizer` interface, I should do it only in geoserver parser and not in geostyler-style right ?

**Comment by jansule** [comment]
@fgravin The geostyler-style should also be extended, as @KaiVolland explained in https://github.com/geostyler/geostyler/issues/1118#issuecomment-506239726.

**Comment by fgravin** [comment]
> @fgravin The geostyler-style should also be extended, as @KaiVolland explained in [#1118 (comment)](https://github.com/geostyler/geostyler/issues/1118#issuecomment-506239726).

Thanks for answer, I will do it now that my PR on geoserver-parser is ready.

BTW, does it mean that [GeoserverTextSymbolizer](https://github.com/MonsantoCo/geostyler-geoserver-sld-parser/blob/master/src/GeoserverTextSymbolizer.ts) is useless ?

**Comment by jansule** [comment]
Thanks, that's great to hear. 

IMHO it does not make sense to have custom definitions in the parsers themselves. Everything that should be parseable should be part of the geostyler-style, so that other parsers can also use these properties.
