### ISSUE TITLE
Create ArcGis Style Parser

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler#1204]
# Parser Request

**Describe the parser you would like to request**

ArcGis style parser to convert to/from ArcGis styles ~(.style/.stylx)~ (.lyr).

**Additional context**

Could not find a proper style specification of ArcGis styles, but
- https://github.com/nyalldawson/slyr (ArcGis <-> QGIS style converter)
- https://developers.arcgis.com/net/latest/wpf/guide/symbolize-data.htm

might be good starting points.

**Comment by ahocevar** [comment]
I'm currently looking into feasibility of this. A quick preliminary research makes me wonder if this is possible at all with .style files directly, because these are Microsoft Access (.mdb) databases which I could not find a JavaScript based reader/writer without native dependencies for.

There is https://github.com/brianb/mdbtools, which allows reading Microsoft Access files, but not writing. It might be possible to use emscripten to create a JavaScript / Web Assembly version of mdbtools.

Would it be acceptable to require a preparation step, e.g. converting .style files to .csv first?

**Comment by jansule** [comment]
> Would it be acceptable to require a preparation step, e.g. converting .style files to .csv first?

Yes, that is fine. The parser would then be a arcgis-csv-parser. Even though chances are low, but do you know if ArcGis directly supports the export of their styles in other formats?

> There is https://github.com/brianb/mdbtools, which allows reading Microsoft Access files, but not writing. It might be possible to use emscripten to create a JavaScript / Web Assembly version of mdbtools.

That would be a nice thing. IMHO reading the styles is the more important part in that case.

**Comment by ahocevar** [comment]
@jansule 

> Even though chances are low, but do you know if ArcGis directly supports the export of their styles in other formats?

This does not appear to be the case for ArcGIS Desktop. I thought that when publishing maps with ArcGIS Server, which supports WMS, it would be possible to provide a `GetStyles` endpoint. But the [documentation](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/wms-services.htm#GUID-6115EF82-3DD2-4AC0-BA69-B3D9FD536FF0) is unclear about that. It might be that that endpoint is only available for manually created SLD files. It would be good if someone who has access to and is familiar with ArcGIS Server could shed more light on this.

**Comment by ahocevar** [comment]
Here are my findings:

### Documentation of the .style format

The format is proprietary and undocumented by the vendor. North Road's open source version of [Slyr](https://github.com/nyalldawson/slyr) has only a rudimentary description of the basics of how [styles are encoded in binary streams](https://github.com/nyalldawson/slyr/blob/2b2115500348fd4a61f7f67b6bde2ad07940ff5f/specs.md#style-binaries). Their parsers are the only usable source for reverse engineering what they were able to find out about the format, e.g. [symbols](https://github.com/nyalldawson/slyr/blob/171a4116e08ecdcef5d312db421f9d10939acfc7/slyr/parser/symbol_parser.py).

It is also worth noting that the Open Source version of Slyr is a fair bit behind the commercial version [https://north-road.com/slyr/] in terms of what can be parsed.

### Reading (and writing) .style files

`.style` files are Microsoft Access database files, just with a different file extension than the default (`.mdb`).

In the GeoStyler ecosystem, the easiest place to do that is when running in Node on Windows, e.g. using [database-js-adodb](https://www.npmjs.com/package/database-js-adodb). This is the only scenario where `.style` files can be read and written.

Read-only access is also possible on Linux, using one of the available Node packages that use [mdbtools](https://github.com/brianb/mdbtools) to read `.mdb` files. Looks like in theory, this approach could also work on MacOS and Windows, but I did not find anything about anyone having accomplished the compilation of mdbtools on these platforms.

In the browser, we're out of luck at the moment. I tried porting mdbtools with [emscripten](https://emscripten.org), but could not get it to compile. It might be possible to accomplish that with significant effort though.

### Conclusion

While I was hoping to be able to deliver a proof-of-concept with at least a very basic point style (e.g. a circle with a given color and radius), I was left with no code at all after two days of research. This does not mean it is impossible to create an ArcGIS style parser, but the effort would be significant.

If there is an interest in persuing this further, we could work on ballpark estimates to get an impression of what effort it might be, what the requirements are (ArcGIS license for reverse engineering etc.), and - more important - what limitations the result would have.

**Comment by jansule** [comment]
@ahocevar 

First of all, thank you for the efforts you put into finding solutions.

I just talked to @hwbllmnn and we think the best way (for now) would be to follow the approach of parsing the Mapbox Style document of the vector tile cache. A wrapper for [geostyler-mapbox-parser](https://github.com/geostyler/geostyler-mapbox-parser) could be implemented that deals with the oddities of the document you mentioned before.

> First of all, and most important, the file format we're looking to support is `.lyr` files, not `.style` files.

That is good to know. I will update the issue description accordingly.

> If there is an interest in persuing this further, we could work together on ballpark estimates to get an impression of what effort it might be, what the requirements are (ArcGIS license for reverse engineering etc.), and - more important - what limitations the result would have.

Maybe @marcjansen can have a say on that.

**Comment by nyalldawson** [comment]
> If there is an interest in persuing this further, we could work together on ballpark estimates to get an impression of what effort it might be, what the requirements are (ArcGIS license for reverse engineering etc.), and - more important - what limitations the result would have.

From my personal experience: about 4-6 months of painstaking, brain melting, full-time development 😭 I will release the full specs openly via slyr as soon as I've recovered costs on this though!

**Comment by jansule** [comment]
@nyalldawson thanks for joining the discussion.

Having access to the specs would be a huge step forward, so thanks for that, too!

Without having any official specs from ESRI, I just can guess how painstaking writing that parser has to be...

**Comment by nyalldawson** [comment]
> Without having any official specs from ESRI, I just can guess how painstaking writing that parser has to be...

It's horrible. It's a binary format which seems to have been developed by a bunch of different teams in isolation and with no particular conventions. So the serialisation formats used for styles is totally different to vector layers vs raster layers vs remote layers. The rules keep changing the deeper you get... and there's no error handling possible in the format, so without full knowledge of EVERYTHING in an mxd document, you can only read a very small subset of it :cry:

**Comment by marcjansen** [comment]
I think we ca put this issue oin hold, right? No real promising way forward.

**Comment by syncush** [comment]
Hi!
I was searching for a way to convert `.lyrx` -> `Mapbox style` in order to be able to serve vector tiles using open-source map components (OpenLayers, leaflet, MapboxGL JS v1) and an open-source vector tile server ([tegola](https://tegola.io/)), after long days of searching I did not find a tool that can directly make this conversion. Then I encountered `VTPK` and thought maybe it can be leveraged for my needs. So my new plan was `.lyrx` -> `.vtpk` (using ArcPro) -> `Mapbox style`.
 
## [VTPK](https://pro.arcgis.com/en/pro-app/latest/tool-reference/data-management/create-vector-tile-package.htm)
### Overview
VTPK is a complete vector tile package (the equivalent of  [`.mbtiles`](https://docs.mapbox.com/help/glossary/mbtiles/#:~:text=MBTiles%20is%20a%20file%20format,For%20example%2C%20mapbox.&text=MBTiles%20can%20contain%20raster%20or,the%20Mapbox%20Studio%20tilesets%20page.) ) created by ArcPro (ESRI). It contains zipped folders and files which are resources used for MVT serving and styling. The zip archive can be easily extracted.

### Folder structure
At the root path, there will be two folders:
1. esriinfo
2. p12
 
Inside `/p12/resources` folder, there are the following folders:
1. `styles` folder holds a root.json file which is a `Mapbox-gl-style map`. Some resources inside the map must be changed because VTPK assumes all content is available inside the package. Sprites, glyphs, and URL of the sources must point to the appropriate services.

2.  `sprites` folder holds a sprite files (JSON and png and in @2x versions) file which must be served for the sprites to be fetched on map load.

3.  `glyphs` folder holds font folders that contain PBF files for Unicode ranges. These files must be served for labels to be fetched once the map uses them.

---------------

Unfortunately, I did not succeed in my attempt since `VTPK` style file uses `_symbol` field for some layers as a filter (perhaps for other properties too), which is a field appended to the mvt the VTPK holds but the data source is not.

Do you think VTPK can help in any way to be to parse `.lyrx` -> `Mapbox gl`?

**Comment by jansule** [comment]
Thanks for the info! This might be an applicable approach.

I would love to hear @ahocevar's opinion on that.

@syncush Is it possible to share some example VTPK styles with us, so that we can have a look at this?

**Comment by ahocevar** [comment]
Exporting a vector tile cache or VTPK from Esri is definitely the way to go.

**Comment by syncush** [comment]
Hi @jansule, 
I can not provide a `lyrx` file with a matching `vtpk`, but I can supply a vtpk from Austria gov site

https://github.com/syncpoint/openvtpk

https://www.data.gv.at/?s=basemap.at 

https://www.data.gv.at/katalog/dataset/b694010f-992a-4d8e-b4ab-b20d0f037ff0

link for downloading a vtpk (warning, big file, few GBs):
https://www.data.gv.at/katalog/dataset/basemap-at-verwaltungsgrundkarte-vektor-offline-osterreich/resource/51ee1bf4-dbfd-4c46-84b7-32045a810b82

**Comment by jansule** [comment]
More or less. Due to time limitations, we did not yet manage to actively continue this issue. But it is still on the roadmap.
