### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler#505]
Due to the increasing size of the parsers and UIComponents we're loosing performance. We should investigate what causes the laggy behaviour and then fix it.

e.g. `shouldComponentUpdate` could help fixing problems with the UI performance.

**Comment by KaiVolland** [comment]
Note: The `CodeEditor` component seems to slow down the application a lot.

**Comment by jansule** [comment]
I made some simple performance checks. So far, we have two main problems here:
1. **every component will be re-rendered as soon as the style changes.** This also affects components that should actually not be updated, e.g. if there are changes in Rule1, Rule2 will also be updated, if there are changes in a symbolizer, filter will also be updated. React re-renders all subcomponents of a component that called setState, which in our case is the whole App.

2. `CodeEditor` **calls the active parser on each and every change.** E.g. if I replace a color value `#000000` to `#FFFFFF`, the style will be parsed 12 times! Once for every removal/addition of a char.

To counteract the first problem, we can use `shouldComponentUpdate()` at relevant parts to make sure that subcomponents only render if a relevant part of a style changed. Below images show the perfomance when removing and afterwards adding two characters in the `CodeEditor`, with and without `shouldComponentUpdate()`.

**Image1:** Changes in `CodeEditor` and collapsed `FilterTree`.  
_Upper Plot_: without `shouldComponentUpdate()`.  
_Lower Plot_: with  `shouldComponentUpdate()` on `FilterTree` and `ScaleDenominator`.
![image](https://user-images.githubusercontent.com/12186477/47788683-b889f980-dd12-11e8-8af5-d5d3223d6070.png)

**Image2:** Changes in `CodeEditor` and expanded `FilterTree`.  
_Upper Plot_: without `shouldComponentUpdate()`.  
_Lower Plot_: with  `shouldComponentUpdate()` on `FilterTree` and `ScaleDenominator`.
![image](https://user-images.githubusercontent.com/12186477/47789750-ba08f100-dd15-11e8-9f29-dea144aae9af.png)


It already shows clear performance improvements. The red ticks show, where the performance is very slow due to the bad performance of `CodeEditor`.

**Comment by KaiVolland** [comment]
I thought about delaying the call of the change listeners for input fields as the `CodeEditor`.

This way we only call the `onStyleChange` function once the input is done.

e.g. for the `CodeEditor` which waits for 500ms before firing the change callback (untested code):

```diff
diff --git a/src/Component/CodeEditor/CodeEditor.tsx b/src/Component/CodeEditor/CodeEditor.tsx
index f70988e..0b2a5b2 100644
--- a/src/Component/CodeEditor/CodeEditor.tsx
+++ b/src/Component/CodeEditor/CodeEditor.tsx
@@ -56,6 +56,8 @@ interface CodeEditorState {
  */
 class CodeEditor extends React.Component<CodeEditorProps, CodeEditorState> {
 
+  _onStyleChangeTimeout: any;
+
   constructor(props: CodeEditorProps) {
     super(props);
     this.state = {
@@ -125,22 +127,33 @@ class CodeEditor extends React.Component<CodeEditorProps, CodeEditorState> {
       value,
       invalidMessage: undefined
     });
-    try {
-      this.styleFromValue(value)
-        .then((style: GsStyle) => {
-          if (this.props.onStyleChange) {
-            this.props.onStyleChange(style);
-          }
-        }).catch(err => {
+
+    if (this._onStyleChangeTimeout) {
+      clearTimeout(this._onStyleChangeTimeout);
+    }
+
+    this._onStyleChangeTimeout = setTimeout(
+      () => {
+        try {
+          this.styleFromValue(value)
+            .then((style: GsStyle) => {
+              if (this.props.onStyleChange) {
+                this.props.onStyleChange(style);
+              }
+            }).catch(err => {
+              this.setState({
+                invalidMessage: err.message
+              });
+            });
+        } catch (err) {
           this.setState({
-            invalidMessage: err.message
+            invalidMessage: 'Error'
           });
-        });
-    } catch (err) {
-      this.setState({
-        invalidMessage: 'Error'
-      });
-    }
+        }
+      },
+      500
+    );
+
   }

```

**Comment by KaiVolland** [comment]
Pure code might be better readable then the diff:
```javascript
    if (this._onStyleChangeTimeout) {
      clearTimeout(this._onStyleChangeTimeout);
    }

    this._onStyleChangeTimeout = setTimeout(
      () => {
        try {
          this.styleFromValue(value)
            .then((style: GsStyle) => {
              if (this.props.onStyleChange) {
                this.props.onStyleChange(style);
              }
            }).catch(err => {
              this.setState({
                invalidMessage: err.message
              });
            });
        } catch (err) {
          this.setState({
            invalidMessage: 'Error'
          });
        }
      },
      500
    );
```

**Comment by jansule** [comment]
Sounds like a good idea. I just wrapped the old `onChange` function into a `handleOnChange`. This might be easier to maintain and works fine, too.

```javascript
// src/Component/CodeEditor/CodeEditor.tsx

handleOnChange = (editor: any, data: any, value: string) => {
  clearTimeout(this.editTimeout);
  this.editTimeout = setTimeout(() => {
    console.log('calling onChange');
    this.onChange(editor, data, value);
  }, 500);
}


<CodeMirror
  className="gs-code-editor-codemirror"
  value={value}
  autoCursor={false}
  options={{
  gutters: ['CodeMirror-lint-markers'],
  lint: true,
  mode: this.getModeByParser(),
  lineNumbers: true,
  lineWrapping: true
  }}
  onChange={this.handleOnChange}
/>
```

**Comment by jansule** [comment]
We can declare components with simple props and states as `PureComponents`. These components already call `shouldComponentUpdate()` with a shallow comparison. This could reduce code.

> React.PureComponent is similar to React.Component. The difference between them is that React.Component doesn’t implement shouldComponentUpdate(), but React.PureComponent implements it with a shallow prop and state comparison.
[https://reactjs.org/docs/react-api.html#reactpurecomponent](https://reactjs.org/docs/react-api.html#reactpurecomponent)

This is especially applicable for the input fields. Then, we have to implement `shouldComponentUpdate()` only for the other components.

**Comment by KaiVolland** [comment]
> Sounds like a good idea. I just wrapped the old `onChange` function into a `handleOnChange`. This might be easier to maintain and works fine, too.
> …

Little overarchitectured from my perspective, as we allready wrap it in `this.onChange` but I won't block it.
